dz
htmlacademy-adaptive/1688167-pink-24 pull request #2
Opened 2021-11-28 13:50 UTC by IvoLord

2021-11-28 20:37 UTC, andreysgra requested changes

2021-11-28 20:37 UTC, andreysgra commented on source/index.html
> +          <li class="rewiew__pagination-item">
Ошибка именования классов по БЭМ. Банальная опечатка в названии `rewiew`.

Проверить правильность именования классов можно [здесь](https://yoksel.github.io/html-tree/).

2021-11-28 20:37 UTC, andreysgra commented on source/index.html
> +        <p class="comtacts__title">Остались вопросы? Свяжитесь с нами!</p>
Здесь тоже опечатка в слове `comtacts`.

2021-11-28 20:37 UTC, andreysgra commented on source/index.html
> +            <p class="contacts-item__text">ул. Большая Конюшенная, 19/8</p>
А здесь ошибка другого рода. Префикс `contacts-item__` указывает на то, что это элемент блока `contacts-item`, но блока такого нет, а есть блок `contacts`.

2021-11-28 20:37 UTC, andreysgra commented on source/index.html
> +        </button>
Согласитесь, что странно то, что кнопка "Открыть меню" является частью главной навигации сайта, а ссылка-логотип `page-header__logo` туда не входит.

2021-11-28 20:37 UTC, andreysgra commented on source/index.html
> +      </section>
Советую весь этот контент
![image](https://user-images.githubusercontent.com/17790771/143784505-41478fd5-0389-4908-952b-13f928872935.png)
разместить в хэдере. Посмотрите макеты планшета и десктопа - там происходит перестроение блоков, а также у хэдера и секции общий фон. Если размещать данную секцию в `main`, то впоследствии придётся идти на разные ухищрения, а зачем, если всё можно сделать проще.

2021-11-28 20:37 UTC, andreysgra commented on source/index.html
> +        </button>
А с каких пор такой элемент интерфейса размечается кнопкой? 😏 А ещё у нас есть такой [пункт](https://up.htmlacademy.ru/adaptive/24/project/pink#pink-4-2) ТЗ.

2021-11-28 20:37 UTC, andreysgra commented on source/index.html
> +              </a>
Про эти ссылки есть описание [здесь](https://up.htmlacademy.ru/adaptive/24/project/pink#pink-4-3).

2021-11-28 20:37 UTC, andreysgra commented on source/index.html
> +              <img src="img/yes.svg" width="31" height="21" alt="Есть" />
Это же всё декоративные изображения
![image](https://user-images.githubusercontent.com/17790771/143784750-0fb704d4-724d-41a3-b1d3-771a5317c601.png)
Зачем их добавлять в разметку?

2021-11-28 20:37 UTC, andreysgra commented on source/index.html
> +            <h3 class="contacts-item__title">Приезжайте в гости:</h3>
**Звоните, Пишите, Приезжайте в гости** - ну разве ж это заголовки? Конечно, нет.

2021-11-28 20:37 UTC, andreysgra commented on source/index.html
> +            <p class="contacts-item__text">+7 (812) 555-66-66</p>
Это стоит разметить ссылкой протоколом `tel`.

2021-11-28 20:37 UTC, andreysgra commented on source/index.html
> +            <p class="contacts-item__text">mail@htmlacademy.ru</p>
Это стоит разметить ссылкой протоколом `mailto`.

2021-11-28 20:37 UTC, andreysgra commented on source/index.html
> +        </a>
А зачем для карты ссылка? Тут обёртка в виде `div` нужна.

2021-11-28 20:37 UTC, andreysgra commented on source/index.html
> +            <img src="img/youtube.svg" width="15" height="13" alt="YouTube." />
Иконки соцсетей - декоративные изображения.

2021-11-29 09:55 UTC, IvoLord commented on source/index.html
> +              <img src="img/yes.svg" width="31" height="21" alt="Есть" />
думал что если не сработае css то не будет в разметке видно тарифный план

2021-11-29 14:03 UTC, andreysgra commented on source/index.html
> +          <!-- ? обязательно менять было клас с page-header__logo на main-nav__logo ? -->
Нет, не обязательно, так как `page-header` является родителем по отношению к логотипу.

2021-11-29 14:03 UTC, andreysgra commented on source/index.html
> +              <img src="img/yes.svg" width="31" height="21" alt="Есть" />
Так можно добавить поясняющий текст в скрытый `span`.

2021-11-29 14:05 UTC, andreysgra approved these changes

2021-11-29 14:05 UTC, andreysgra commented on source/index.html
> +            <td class="price-table__cell">Коментаии</td>
```suggestion
            <td class="price-table__cell">Комментарии</td>
            <td class="price-table__cell">Комментарии</td>
            <td class="price-table__cell">Комментарии</td>
```

2021-11-29 14:05 UTC, merged