Module2 task2
htmlacademy-adaptive/1688167-pink-24 pull request #3
Opened 2021-11-30 22:47 UTC by IvoLord

2021-12-01 12:13 UTC, andreysgra requested changes
В странице формы не размечены эти блоки:

![image](https://user-images.githubusercontent.com/17790771/144232555-a55caa59-f3fa-4d94-a31d-1aa0d070a949.png)

![image](https://user-images.githubusercontent.com/17790771/144232611-2789405a-c23f-4c14-942d-00962eb389ab.png)

2021-12-01 12:13 UTC, andreysgra commented on source/catalog.html
> +            />
Страдает форматирование кода: предыдущие input `type"range"` написаны в одну строку.

2021-12-01 12:13 UTC, andreysgra commented on source/catalog.html
> +          <button class="add-photo__button" type="button">Запостить</button>
`type="submit"`

2021-12-01 12:13 UTC, andreysgra commented on source/catalog.html
> +          <button class="add-photo__button" type="button">Отменить</button>
`type="reset"`

2021-12-01 12:13 UTC, andreysgra commented on source/form.html
> +        <fieldset class="concourse-form__group">
В форме множество проблем с именованием классов по БЭМ. Проверьте здесь https://yoksel.github.io/html-tree/

2021-12-01 12:13 UTC, andreysgra commented on source/form.html
> +      >
Тоже можно сделать заголовком первого уровня.

2021-12-01 12:13 UTC, andreysgra commented on source/form.html
> +      <h1 class="visually-hidden">Форма для конкурса</h1>
А здесь `h1` убрать.

2021-12-01 12:13 UTC, andreysgra commented on source/form.html
> +          </p>
Ведь можно (и нужно) текст, который вы поместили в параграф, перенести в легенду. Тогда и легенду не нужно прятать и параграф становится ненужным.

2021-12-01 12:13 UTC, andreysgra commented on source/form.html
> +          </p>
По легенде тоже самое.

2021-12-01 12:13 UTC, andreysgra commented on source/form.html
> +          <p class="concourse-form__group-title">Опишите свои эмоции</p>
По легенде тоже самое.

2021-12-01 12:13 UTC, andreysgra commented on source/form.html
> +            <textarea class="concourse-form__input" name="comment"></textarea>
Пропущен `placeholder` с текстом.

2021-12-01 12:13 UTC, andreysgra commented on source/form.html
> +        </button>
Ну разве простая кнопка может что-то отравить в форме? Это `type="submit"`.

2021-12-02 14:44 UTC, andreysgra requested changes
Ошибка валидации HTML главной страницы
![image](https://user-images.githubusercontent.com/17790771/144444043-de2c3483-2bb0-471a-aa55-7036cf2be97a.png)

2021-12-02 14:44 UTC, andreysgra commented on source/catalog.html
> +              <button class="gallery__like">
Не указан тип кнопки (во всех карточках галереи).

2021-12-02 14:44 UTC, andreysgra commented on source/catalog.html
> +                <div class="gallery__like-icon"></div>
А зачем в кнопке лишний элемент разметки, который будет использоваться только под изображение? Ну и кроме того `div` нельзя размещать внутри кнопки. Даже если это всё
![image](https://user-images.githubusercontent.com/17790771/144229354-16f22df2-d67d-4a29-8a31-def6c12fd12e.png)
рассматривать как одно целое - кнопку, то изображение сердечка можно нарисовать фоном в левой части кнопки, задав соответствующий паддинг слева. Однако кнопкой можно сделать только "сердечко", а текст "нравится" уже отдельным элементом.

2021-12-02 14:44 UTC, andreysgra commented on source/form.html
> +стесняясь в выражениях"
Форматирование кода! За это сильно ругают на защите - [Б28](https://up.htmlacademy.ru/adaptive/24/criteries#b28).

2021-12-02 14:44 UTC, andreysgra commented on source/form.html
> +        </div>
Эти блоки не являются частью формы. Это информационные сообщения. Так как это модальные окна, то как правило их размещают в конце разметки, после тега `footer`.

2021-12-02 14:44 UTC, andreysgra commented on source/form.html
> +          <span class="concourse-form__required-info--color">*</span> —
Это класс модификатора, а он не может использоваться самостоятельно.

2021-12-02 14:44 UTC, andreysgra commented on source/form.html
> +              res
`res` - что-то постороннее.

2021-12-02 20:37 UTC, IvoLord commented on source/catalog.html
> +                <div class="gallery__like-icon"></div>
я сделал пустой блок для того что думал что бы сделать переключение лайка, вкл\выкл через класс, мог когда кликнул сам

2021-12-02 20:40 UTC, IvoLord commented on source/form.html
> +стесняясь в выражениях"
Prettier переносит все так, еще не знаю до конца как его настроить как нужно мне (((

2021-12-02 20:44 UTC, IvoLord commented on source/form.html
> +          <span class="concourse-form__required-info--color">*</span> —
понял, а то думал и не понимал, чего оно ругается...

2021-12-02 21:08 UTC, IvoLord commented on source/form.html
> +стесняясь в выражениях"
хотя нет, был таки перенос на новую строку(

2021-12-03 09:10 UTC, merged