update
htmlacademy-adaptive/1688167-pink-24 pull request #5
Opened 2021-12-11 23:59 UTC by IvoLord

2021-12-12 12:13 UTC, andreysgra requested changes

2021-12-12 12:13 UTC, andreysgra commented on source/sass/components/visualy-hidden.scss
> +}
Файл **visually-hidden.scss** нужно вынести из папки **components**, так как `.visually-hidden` является служебным классом. Поместить в папку **source/sass/global/**.

2021-12-12 12:13 UTC, andreysgra commented on source/sass/components/main-nav.scss
> +}
Абсолютное позиционирование меню нужно только при включённом JavaScript. Всё это описано в критерии [Б30](https://up.htmlacademy.ru/adaptive/24/criteries#b30). Изначально, без JS меню остаётся в потоке. А для работы с JS нужен будет отдельный класс.

2021-12-12 12:13 UTC, andreysgra commented on source/sass/components/main-nav.scss
> +  justify-content: center;
А без `flex` никак не выровнять текст по центру? 😏

2021-12-12 12:13 UTC, andreysgra commented on source/sass/components/main-nav.scss
> +  height: 63px;
`min-height`

2021-12-12 12:13 UTC, andreysgra commented on source/sass/components/page-footer.scss
> +  }
А для чего вы используете псевдо элементы, да ещё и с абсолютным позиционированием? По другому разве иконки добавить нельзя?

2021-12-12 12:13 UTC, andreysgra commented on source/sass/global/global.scss
> +}
Критерий [Д16](https://up.htmlacademy.ru/adaptive/24/criteries#d16).

2021-12-12 12:13 UTC, andreysgra commented on source/sass/global/global.scss
> +}
Тег `body` имеет класс БЭМ элемента `.page__body`, так почему бы эти все свойства не описать в классе `.page__body`, а класс разместить в файле **page.scss** ?

2021-12-14 11:25 UTC, IvoLord commented on source/sass/components/button.scss
> +  align-items: center;
эти свойства нужны для того, когда есть ссылка выглядящая как кнопка и ей отцентровать текст поцентру

2021-12-14 12:03 UTC, IvoLord commented on source/sass/components/main-nav.scss
> +  justify-content: center;
для меня сейчас кажись никак, это как я вижу это самый простой и действенный способ который если что, еще и позволяет подстраиваться под изменения

2021-12-14 12:29 UTC, IvoLord commented on source/sass/components/page-footer.scss
> +  }
когда это писал, так и казалось что, что то я тут горожу не то ( исправил

2021-12-15 09:39 UTC, andreysgra commented on source/sass/components/button.scss
> +  align-items: center;
Так для изменения положения текста существует свойство `text-align`, а по высоте текст можно отцентрировать с помощью вертикальных паддингов кнопки.

Конечно, вариант с использованием флекса для центрирования текста работает, но честно говоря применение немного странное.

2021-12-16 16:12 UTC, andreysgra requested changes
В прошлый раз забыл написать. Есть проблемы с лишними файлами, которых в проекте быть не должно и проблемы с наименованием файлов:
1. zip-архив удалить
![image](https://user-images.githubusercontent.com/17790771/146407287-2e532156-46a8-4771-9bf3-d258c495a047.png)
2. Заглавные буквы и пробелы в названии
![image](https://user-images.githubusercontent.com/17790771/146407694-45672a70-92ad-4c50-ac9f-ab406a2efb98.png)

2021-12-16 16:12 UTC, andreysgra commented on source/sass/global/global.scss
> +}
Это по всему определению служебные классы единственная цель которых обнуление дефолтных свойств элемента. С БЭМ это не очень хорошо сочетается, так как основная самостоятельная единица БЭМ - блок, должна содержать все необходимые свойства, чтобы её можно было использовать не только рамках данного проекта, но даже и в другом, без внесения изменений. А если часть свойств будет изменяться через подобные служебные классы, которые при переносе в другой проект могут потеряться, то суть БЭМ искажается.

Так что эти классы нужно удалить, а обнуление свойств списка делать в конкретном классе.

2021-12-17 10:44 UTC, IvoLord commented on source/sass/global/global.scss
> +}
понял

2021-12-24 17:34 UTC, andreysgra approved these changes

2021-12-24 17:34 UTC, andreysgra commented on source/sass/components/catalog/gallery.scss
> +  list-style: nne;
`list-style: none`
Но и оно не нужно, так как в строке 19 объявлено это свойство.

2021-12-24 17:35 UTC, merged